name: run
on:
  schedule:
    - cron: '25,55 0-6,22-23 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          pip3 install httpx
          python3 run.py
